spring.application.name=auth-service
server.port=8080

# ===== Aurora PostgreSQL Serverless v2 =====
spring.datasource.url=jdbc:postgresql://shopease-db-instance-1.cjuoiu4oi4x7.ap-south-1.rds.amazonaws.com:5432/shopease
spring.datasource.username=shopease_admin
spring.datasource.password=Adminuser123
spring.datasource.driver-class-name=org.postgresql.Driver

# ===== JPA / Hibernate =====
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# ===== JWT =====
app.jwt.secret=ShopEaseSecretKey2026SuperSecureLongKeyForJWTTokenGeneration1234567890
app.jwt.expiration-ms=86400000

# ===== AWS =====
aws.region=ap-south-1
aws.sns.topic-arn=arn:aws:sns:ap-south-1:483829975256:shopease-signup-topic
