# ============================================
# Shopease: product-service deployment
# Author: Sanket Mule
# ============================================

apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service-deployment
  namespace: shopease-webapp-development
  labels:
    app: product-service-deployment

spec:
  replicas: 2
  selector:
    matchLabels:
      app: product-service-deployment
  template:
    metadata:
      labels:
        app: product-service-deployment
    spec:
      containers:
      - name: product-service-workload
        image: 483829975256.dkr.ecr.ap-south-1.amazonaws.com/product-service:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 8081

        resources:
          requests:
            cpu: 250m
            memory: 512Mi
          limits:
            cpu: 500m
            memory: 1Gi

        startupProbe:
          httpGet:
            path: /api/products/health
            port: 8081
          failureThreshold: 30
          periodSeconds: 5

        readinessProbe:
          httpGet:
            path: /api/products/health
            port: 8081
          initialDelaySeconds: 10
          periodSeconds: 30
          timeoutSeconds: 3
          failureThreshold: 3

        livenessProbe:
          httpGet:
            path: /api/products/health
            port: 8081
          initialDelaySeconds: 10
          periodSeconds: 30
          timeoutSeconds: 3
          failureThreshold: 3








