# ============================================================================
# ExternalSecret: order-service-secret
# ----------------------------------------------------------------------------
# Syncs AWS secret "shopease/development/order-service" -> K8s Secret of
# the same name in the shopease-webapp-development namespace.
# ============================================================================
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: order-service-secret
  namespace: shopease-webapp-development
  labels:
    app: order-service-deployment
    app.kubernetes.io/name: order-service
    app.kubernetes.io/part-of: shopease-webapp
    app.kubernetes.io/managed-by: external-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: order-service-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: shopease/development/order-service
