apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: order-service-pdb
  namespace: shopease-webapp-development
  labels:
    app: order-service-deployment
    app.kubernetes.io/name: order-service
    app.kubernetes.io/part-of: shopease-webapp
    app.kubernetes.io/managed-by: kubectl

spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: order-service-deployment
  unhealthyPodEvictionPolicy: IfHealthyBudget
