apiVersion: v1
kind: Secret
metadata:
  name: order-service-secret
  namespace: shopease-webapp-development
  labels:
    app: order-service-deployment
    app.kubernetes.io/name: order-service
    app.kubernetes.io/part-of: shopease-webapp

type: Opaque
stringData:
  SPRING_DATASOURCE_PASSWORD: Adminuser123
  APP_JWT_SECRET: ShopEaseSecretKey2026SuperSecureLongKeyForJWTTokenGeneration1234567890
