# ============================================
# Shopease: order-service service
# Author: Sanket Mule
# ============================================

apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: shopease-webapp-development

spec:
  selector:
    app: order-service-deployment
  ports:
    - protocol: TCP
      port: 80         
      targetPort: 8083
  type: ClusterIP
