apiVersion: v1
kind: ConfigMap
metadata:
  name: cart-service-config
  namespace: shopease-webapp-development
  labels:
    app: cart-service-deployment
    app.kubernetes.io/name: cart-service
    app.kubernetes.io/part-of: shopease-webapp

data:
  SPRING_DATASOURCE_URL: jdbc:postgresql://shopease-webapp-development-instance-1.cjuoiu4oi4x7.ap-south-1.rds.amazonaws.com:5432/shopease
  SPRING_DATASOURCE_USERNAME: shopease_admin
