apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-service-config
  namespace: shopease-webapp-development
  labels:
    app: auth-service-deployment
    app.kubernetes.io/name: auth-service
    app.kubernetes.io/part-of: shopease-webapp

data:
  SPRING_DATASOURCE_URL: jdbc:postgresql://shopease-webapp-development-instance-1.cjuoiu4oi4x7.ap-south-1.rds.amazonaws.com:5432/shopease
  SPRING_DATASOURCE_USERNAME: shopease_admin

  APP_JWT_EXPIRATION_MS: "86400000"

  AWS_REGION: ap-south-1
  AWS_SNS_TOPIC_ARN: arn:aws:sns:ap-south-1:483829975256:shopease-signup-topic
