spring.application.name=order-service
server.port=8083

# ===== Aurora PostgreSQL =====
spring.datasource.url=jdbc:postgresql://shopease-db-instance-1.cjuoiu4oi4x7.ap-south-1.rds.amazonaws.com:5432/shopease
spring.datasource.username=shopease_admin
spring.datasource.password=Adminuser123
spring.datasource.driver-class-name=org.postgresql.Driver

# ===== JPA / Hibernate =====
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# ===== JWT =====
app.jwt.secret=ShopEaseSecretKey2026SuperSecureLongKeyForJWTTokenGeneration1234567890

# ===== Cart Service URL =====
app.cart-service.url=http://cart-service.shopease-webapp-development.svc.cluster.local:80
